spring:
  application:
    name: roast-my-resume
  ai:
    ollama:
      base-url: http://localhost:11434
      model: mistral

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.roastmyresume: DEBUG
